### ISSUE TITLE
Crashing Internet Explorer

### ISSUE THREAD

**Issue by fnoks** [otacke/h5p-timer#3]
H5P.Timer is using Number.isInteger() wich is not supported by Internet Explorer. I hope you are able to fix this one quickly, since it affects everyone using Memory Game in IE, including the front-page on h5p.org.

**Comment by otacke** [comment]
Polyfill to the rescue. I'm going to fix it tonight.

**Comment by otacke** [comment]
@fnoks 
Since I only own a Linux system at home, I chose to take an extra break and fix the issue now. I'd not be able to test it on IE before tomorrow otherwise. The branch at https://github.com/otacke/h5p-timer/tree/polyfill_isInteger seems to do the job on IE, and I also had a look on Chrome (Desktop and Android) and Firefox. Could you please tell me if it works with other browsers that I don't have access to right now? If yes, you're good to go and I'll merge my changes to the master branch.

**Comment by fnoks** [comment]
@otacke : Even if you mentioned me, I did not get any email notification. Anyways, thank you for the quick processing of this one - I will do some testing of this tomorrow at latest.

**Comment by otacke** [comment]
@fnoks Sure thing! My bug, my responsibility.

**Comment by icc** [comment]
The fix works perfectly, good work!

**Comment by otacke** [comment]
Don't worry. I'm going to include some fresh bugs elsewhere ;-)
